### ISSUE TITLE
[Bug] datagrid resizing in RTL

### ISSUE THREAD

**Issue by avrahamcool** [adarshpastakia/aurelia-ui-framework#92]
hi @adarshpastakia 
there is a problem when resizing columns in RTL mode.
1) there is a dotted line that indicates the column that is being resized - in RTL it is shown in the wrong place.
2) if you resize the column to a large enough width, a horizontal scrollbar should appear. doesn't work in RTL.

here is a screen capture of the problem.
![2017-10-30_09-51-21](https://user-images.githubusercontent.com/5445320/32164119-2ba6e65c-bd67-11e7-8e53-eb16b3fa42aa.gif)

**Comment by avrahamcool** [comment]
bug still present in `v4.beta-9`.
1) RTL horizontal scrolling not showing up at all
2) resizable column not resizing (even in LTR)

**Comment by adarshpastakia** [comment]
Fixed in v4.Beta-10

**Comment by avrahamcool** [comment]
both issues are still present in the latest version of the demo.
(maybe it's not reflecting the latest code?)

![2018-01-13_22-39-11](https://user-images.githubusercontent.com/5445320/34909876-beff7816-f8b2-11e7-84d4-5e4003c9fd50.gif)

**Comment by adarshpastakia** [comment]
@avrahamcool  found that the issue exists with chrome and Firefox wherein after scrolling horizontal and switching dir doesn’t reset the horizontal scroll.

So when ltr scrollLeft is used, when switched to rtl they use scrollRight but the scrollLeft does take effect

**Comment by avrahamcool** [comment]
there is no such thing as `scrollRight`.
in `rtl` you have to set `scrollLeft` to negative values.
more on the topic:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft
https://gist.github.com/loominade/4082e9166739e8a25ab5

**Comment by adarshpastakia** [comment]
Ok didn’t look at the property values, so the positive value is moving it the wrong way. Question is how do we observe the change in direction so we can reset the scrollLeft to 0

**Comment by avrahamcool** [comment]
lets say we don't observe that change, we will see a problem with the scrollbar, but when we start to scroll - it should snap into place. right?

we can use the `signal` strategy for this observation.
we should treat the `dir` changes just like `locale` changes..
a custom event should be fired when we change the `dir`, and we can make the scroll re-evaluate when the `dir` changes.
(also, in real life apps, `dir` changes primarily because of `locale` changes)

**Comment by adarshpastakia** [comment]
Yes in an actual app it would be caused by locale change, currently in the demo the dir change is manual and not via a locale change. So we can reset the scroll on locale change, for the demo we can fire the locale:change event manually

**Comment by avrahamcool** [comment]
instead of reseting to `0`, I think its better to multiply by `-1`

**Comment by ronenziv** [comment]
hi, we have the same problem at ui-datagrid,  a horizontal scrollbar that should appear, doesn't work in RTL.

**Comment by avrahamcool** [comment]
very good news. thanks @adarshpastakia .
just FYI, Ill try to contribute more in the near future.
(I don't have a lot of free time lately)

**Comment by avrahamcool** [comment]
the issue with `rtl` resizing is still present.
I pretty sure I've tested it and saw it work.. but now it's not working in the demo site.
scroller is not visible at all in `rtl` mode.

**Comment by adarshpastakia** [comment]
@avrahamcool something is weirdly wrong, its working on safari but not on chrome.
